name: GitHub Metrics

on:
  schedule:
    - cron: "0 9 * * *"   # todo dia 09:00 UTC (ajustável)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate metrics
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: tamm619
          template: classic
          filename: assets/metrics.svg

          # Visual
          config_display: large
          config_octicon: yes
          config_timezone: America/Sao_Paulo

          # Seções (bem “recrutador friendly”)
          base: header, activity, repositories

          # Plugins bons e leves
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 8

          plugin_notable: yes
          plugin_notable_from: all
          plugin_notable_types: commit

          plugin_stars: yes
          plugin_stars_limit: 6
